<?php
require_once '../includes/config.php';
require_once '../includes/auth.php';

$auth->requireLogin();
$user = $auth->getCurrentUser();

$generation_id = filter_var($_GET['id'], FILTER_VALIDATE_INT);
if (!$generation_id) {
    http_response_code(400);
    exit('Invalid ID');
}

// Get the generation
global $db;
$stmt = $db->prepare("SELECT prompt, output FROM articles WHERE id = ? AND user_id = ?");
$stmt->bind_param("ii", $generation_id, $user['id']);
$stmt->execute();
$result = $stmt->get_result();

if ($result->num_rows === 0) {
    http_response_code(404);
    exit('Content not found');
}

$generation = $result->fetch_assoc();

// Set headers for download
header('Content-Type: text/plain');
header('Content-Disposition: attachment; filename="omniseo-content-' . $generation_id . '.txt"');
header('Content-Length: ' . strlen($generation['output']));

echo "Generated by " . SITE_NAME . "\n";
echo "Prompt: " . $generation['prompt'] . "\n";
echo "Generated on: " . date('Y-m-d H:i:s') . "\n";
echo str_repeat('-', 50) . "\n\n";
echo $generation['output'];
?>
